web:
  build: .
  expose:
    - "8443"
  links:
    - db
    - email
    - pdf
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_marketplace_sec
db:
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=db_marketplace_sec
  image: mysql:5.6
email:
  build: executables/Mailing
  expose:
    - "10001"
  links:
    - db
pdf:
  build: executables/PDF
  expose:
    - "10000"
  links:
    - db
web2:
  build: .
  expose:
    - "8444"
  links:
    - db
    - email
    - pdf
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_marketplace_sec
lb:
    image: haproxy:2.1.4
    ports:
      - "9090:443" # Only service that is exposed to the host is the lb 
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      #- "./xip.io.pem:/etc/ssl/xip.io/xip.io.pem:ro"
    restart: unless-stopped