web:
  build: .
  ports:
    - "8443:8443"
  links:
    - db
#    - email
#    - pdf
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_marketplace_sec
db:
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=db_marketplace_sec
  image: mysql:5.6
#email:
#  build: executables/Mailing
#  expose:
#    - "10001"
#  links:
#    - db
#pdf:
#  build: executables/PDF
#  expose:
#    - "10000"
#  links:
#    - db