version: "3.7"
services:


  web:
    build: .
    expose:
      - "8443"
    links:
      - db
      - email
      - pdf
    networks:
      - red1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_marketplace_sec


  db:
    networks:
      - red1
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db_marketplace_sec
    image: mysql:5.6
    
  email:
    build: executables/Mailing
    networks:
      - red1
    expose:
      - "10001"
    links:
      - db


  pdf:
    build: executables/PDF
    networks:
      - red1
    expose:
      - "10000"
    links:
      - db


  web2:
    build: .
    expose:
      - "8443"
    networks:
      - red1
    links:
      - db
      - email
      - pdf
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_marketplace_sec


  lb:
      image: haproxy:2.1.4
      ports:
        - "443:443"
        - "8404:8404"
      networks:
        - red1
      volumes:
        - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      links:
        - web
        - web2
      restart: unless-stopped


networks:
    red1:
      driver: bridge
